plugins {
    id 'java-library'
    id 'architectury-plugin' version '3.4-SNAPSHOT'
    id 'dev.architectury.loom' version '1.7-SNAPSHOT' apply false
    id "io.github.pacifistmc.forgix" version "1.2.9"
}

architectury {
    minecraft = rootProject.minecraft_version
}

subprojects {
    apply plugin: 'dev.architectury.loom'

    repositories {
        maven {
            name = 'ParchmentMC'
            url = 'https://maven.parchmentmc.org'
        }

        maven {
            name = 'JitPack'
            url = 'https://jitpack.io'
            content {
                includeGroup "com.github.Luke100000"
            }
        }

        flatDir {
            dirs '../libs'
        }
    }

    dependencies {
        minecraft "com.mojang:minecraft:${project.minecraft_version}"
        mappings loom.layered() {
            officialMojangMappings()
            parchment("org.parchmentmc.data:parchment-1.20.1:2023.09.03@zip")
        }

        modImplementation 'com.github.Luke100000:minecraft-comes-alive:26648fa29bc596300cc66f760671ceceaca12d61'

        implementation 'com.google.code.findbugs:jsr305:3.0.2'
    }
}

allprojects {
    apply plugin: "maven-publish"
    apply plugin: 'architectury-plugin'

    group = rootProject.groupId
    description = rootProject.displayname
    archivesBaseName = rootProject.name
    version = mod_version

    build.finalizedBy(mergeJars)
    assemble.finalizedBy(mergeJars)

    java {
        withSourcesJar()

        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    tasks.withType(JavaCompile).configureEach {
        it.options.release = 17
    }

    task sourceJar(type: Jar) {
        archiveClassifier.set('sources')
        from sourceSets.main.allJava
    }

    artifacts {
        archives sourceJar
    }

    publishing {
        publications {
            mavenJava(MavenPublication) {
                artifact jar
                artifact sourceJar
            }
        }
        repositories {
            maven {
                url "file://${project.projectDir}/mcmodsrepo"
            }
        }
    }
}

forgix {
    group = rootProject.groupId
    mergedJarName = "${rootProject.name}-${rootProject.version}-universal.jar"
    outputDir = "build/libs"

    forge {
        jarLocation = "build/libs/${rootProject.name}-${rootProject.version}.jar"
        mixin "mca.mixin.json"
    }

    fabric {
        jarLocation = "build/libs/${rootProject.name}-${rootProject.version}.jar"
    }

    quilt {
        jarLocation = "build/libs/${rootProject.name}-${rootProject.version}.jar"
    }
}