plugins {
    id 'multiloader-common'
    id 'net.neoforged.moddev.legacyforge'
    id "idea"
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}

legacyForge {
    mcpVersion = minecraft_version
    if (file("src/main/resources/META-INF/accesstransformer.cfg").exists()) {
        accessTransformers = ["src/main/resources/META-INF/accesstransformer.cfg"]
    }
    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }
}

repositories {
    maven {
        name = 'JitPack'
        url = 'https://jitpack.io'
        content {
            includeGroup "com.github.Luke100000"
        }
    }
    flatDir {
        dir '../libs'
    }
}

dependencies {
    compileOnly group: 'org.spongepowered', name: 'mixin', version: '0.8.5'
    implementation group: 'com.google.code.findbugs', name: 'jsr305', version: '3.0.2'

    compileOnly(annotationProcessor("io.github.llamalad7:mixinextras-common:0.4.1"))

    modImplementation "com.github.Luke100000:minecraft-comes-alive:$mca_commit"
}

configurations {
    commonJava {
        canBeResolved = false
        canBeConsumed = true
    }
    commonResources {
        canBeResolved = false
        canBeConsumed = true
    }
}

artifacts {
    commonJava sourceSets.main.java.sourceDirectories.singleFile
    commonResources sourceSets.main.resources.sourceDirectories.singleFile
}