plugins {
    id 'multiloader-common'
    id 'net.neoforged.moddev.legacyforge'
    id "idea"
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}

legacyForge {
    mcpVersion = minecraft_version
    if (file("src/main/resources/META-INF/accesstransformer.cfg").exists()) {
        accessTransformers = ["src/main/resources/META-INF/accesstransformer.cfg"]
    }
    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }
}

repositories {
    maven {
        name = 'Maven from Viola Siemens'
        url = "https://viola-siemens.github.io/pages/maven/"
        content {
            includeGroup "com.hexagram2021"
        }
    }
    maven {
        name = "Fuzs Mod Resources"
        url = "https://raw.githubusercontent.com/Fuzss/modresources/main/maven/"
    }
    maven { // TOP
        name = "Curse Maven"
        url = "https://cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }
    flatDir {
        dir '../libs'
    }
}

dependencies {
    compileOnly group: 'org.spongepowered', name: 'mixin', version: '0.8.5'
    implementation group: 'com.google.code.findbugs', name: 'jsr305', version: '3.0.2'

    compileOnly(annotationProcessor("io.github.llamalad7:mixinextras-common:0.4.1"))
    modCompileOnly group: 'curse.maven', name: 'jade-324717', version: '6271651'

    modImplementation group: 'com.hexagram2021', name: 'chromosomelib-common', version: chromosomelib_version
    modImplementation group: "fuzs.forgeconfigapiport", name: "forgeconfigapiport-fabric", version: forgeconfigapiport_version
}

configurations {
    commonJava {
        canBeResolved = false
        canBeConsumed = true
    }
    commonResources {
        canBeResolved = false
        canBeConsumed = true
    }
}

artifacts {
    commonJava sourceSets.main.java.sourceDirectories.singleFile
    commonResources sourceSets.main.resources.sourceDirectories.singleFile
}